// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var GES, current_path;

    GES = (function() {
      return {
        autoLogin: function() {
          var $auto_fill, $error_msg, auto_msg;

          $auto_fill = $('input:-webkit-autofill');
          if ($auto_fill.length) {
            auto_msg = 'Auto-Logging In';
            $error_msg = $('span[class="error"]').first();
            if ($error_msg.text().search("Please login again.")) {
              $("form:first[method='post']").submit();
              return $('.subcontent.loginsub').after($("<div class='subcontent autologinsub'><h1>" + auto_msg + "</h1></div>"));
            }
          }
        },
        directLinkify: function(anchor_selector) {
          var link, new_url, _i, _len, _ref, _results;

          _ref = $(anchor_selector);
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            link = _ref[_i];
            $(link).attr('onclick', '');
            new_url = link.href.concat('&inpopup=true');
            _results.push($(link).attr('href', new_url));
          }
          return _results;
        },
        addFauxCurrentWeek: function() {
          var $current_week, $faux_week, $go_to_context, $left_col, $right_col, $separator;

          $separator = $('.section.separator').first().clone();
          $current_week = $('.current').first();
          $faux_week = $current_week.clone();
          $faux_week.addClass('fauxWeek').attr('id', 'faux-section');
          $('.weeks tbody').prepend($faux_week);
          $faux_week.after($separator);
          $go_to_context = $('<h3 class="goto-context">Go To Context</h3>');
          $go_to_context.on('click', function() {
            var $real_current_week, $window, el_height, el_offset, el_width, view_port_height, view_port_width;

            $window = $(window);
            view_port_width = $window.width();
            view_port_height = $window.height();
            $real_current_week = $('.realCurrentWeek').first();
            el_width = $realCurrentWeek.width();
            el_height = $realCurrentWeek.height();
            el_offset = $realCurrentWeek.offset();
            return $window.scrollTop(el_offset.top + (el_height / 2) - (view_port_height / 2)).scrollLeftTop(el_offset.left + (el_width / 2) - (view_port_width / 2));
          });
          $('.fauxWeek .weekdates').before($go_to_context);
          $left_col = $('#left-column > div');
          $right_col = $('#right-column > div');
          $left_col.scrollToFixed({
            limit: $('#footer').offset().top - $left_col.outerHeight()
          });
          return $right_col.scrollToFixed({
            limit: $('#footer').offset().top - $right_col.outerHeight()
          });
        },
        addQuickList: function() {
          var $left_col, $new_link, $new_link_item, $quick_list, link, short_name, _i, _len, _ref;

          $left_col = $('#left-column');
          $quick_list = $('<ul>', {
            "class": 'list'
          });
          _ref = $('.name > a');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            link = _ref[_i];
            short_name = link.text.split(' (')[0];
            $new_link = $(link).clone();
            $new_link.text(short_name);
            $new_link_item = $new_link.wrap('<li>').parent();
            $quick_list.append($new_link_item);
          }
          $quick_list = $quick_list.wrap($('<div>', {
            'class': 'content'
          })).parent();
          $quick_list = $quick_list.wrap($('<div>', {
            'class': 'sideblock'
          })).parent();
          $quick_list.prepend($('<div>', {
            'class': 'header',
            'text': 'QuickClick Menu'
          }));
          $quick_list = $quick_list.wrap($('<div>', {
            "class": "quickclick"
          })).parent();
          $quick_list = $quick_list.wrap($('<div>')).parent();
          $quick_list.prependTo($left_col);
          return localStorage["quicklist"] = escape($quick_list.html());
        },
        addCachedQuickList: function() {
          var $quick_list;

          $quick_list = $(unescape(localStorage["quicklist"]));
          $quick_list.find('.header').wrapInner($('<h3>'));
          $quick_list.append('<p>If this menu is out of date, <a href="https://gauchospace.ucsb.edu/courses/">visit the <span class="mycoursebutton">My Courses</span> page while logged in to refresh</a>.</p>');
          $quick_list.append("<p>This is cached from the last logged in user. If auto-login works for you, clicking will auto-log you in through these links if you were logged out from inactivity.</p>");
          $quick_list.append("<p>If you have an issue with this extension, please make an account on <a href='http://github.com'>Github</a> and submit an issue <a href='https://github.com/Roasbeef/GauchoSpace-Enhancement-Suite/issues'>here</a>.");
          return $("#left > a").after($quick_list);
        }
      };
    })();
    current_path = window.location.pathname;
    if (current_path.match(/\/courses\/login\//)) {
      GES.autoLogin();
    } else if (current_path.match(/\/courses\/mod\/resource\//)) {
      GES.directLinkify('.generaltable .c1 a');
    } else if (current_path === "/courses/course/view.php") {
      GES.directLinkify('.activity.resource > a');
      GES.addFauxCurrentWeek();
    } else if (current_path === "/courses/") {
      GES.addQuickList();
    } else if (current_path === "/") {
      GES.addCachedQuickList();
    }
    return $('#menubar').prepend('<li><a href="//gauchospace.ucsb.edu">Front');
  });

}).call(this);

/*
//@ sourceMappingURL=GES.map
*/
